# ---------------------------------------------------------------------------
# Inkfuse Gitlab CI
# ---------------------------------------------------------------------------

stages:
    - test

tests:
    stage: test
    script:
        - clang --version
        - which clang-11
        - which clang-12
        - which clang-12
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja
        - ./tester

linter:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja
        - ninja lint
    allow_failure: true
