# ---------------------------------------------------------------------------
# IMLAB
# ---------------------------------------------------------------------------

stages:
    - test

tests:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja
        - ./tester
        - ./tester_schema
        - ./tester_queryc

linter:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja
        - ninja lint
    allow_failure: true

leaderboard:
    when: manual
    script:
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
        - ninja
        - python3 ../submit_result.py /data/imlab
    tags:
        - leaderboard-imlab
