name: BuildAndTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Run builds and tests both in Debug and RelWithDebInfo
    strategy:
        matrix:
            build_type: [Debug, RelWithDebInfo]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/build
      with:
          - build-type: ${{ matrix.build_type }}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./tester
      
