# Reusable workflow to build certain inkfuse targets.
# Target gets built in ${{ github.workspace }}/build.
name: Build
description: "Build inkfuse using some customization options"

on:
    workflow_call:
        inputs:
            build-type:
                required: true
                description: "Build type - one of {Debug, RelWithDebInfo, Release}"
                type: string
            with-coverage:
                required: false 
                description: "Build with Coverage"
                default: false
                type: bool

jobs:
    runs-on: ubuntu-latest
    steps:
        - name: Configure Coverage
          if: inputs.with_coverage == true
          run: echo "cmake_args=${{ env.cmake_args }} -DWITH_COVERAGE=ON" >> $GITHUB_ENV
        # - name: Show Environment
        #   run: echo "CMake Arguments: ${{ env.cmake_args }}"
        - name: Configure CMake
          run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} ${{ env.cmake_args }}
        - name: Build
          run: cmake --build ${{github.workspace}}/build --config ${{ inputs.build-type }}
      
