name: BuildAndTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    # Run builds and tests both in Debug and RelWithDebInfo
    strategy:
        matrix:
            build-type: [Debug, RelWithDebInfo]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/build.yml
      with:
          build-type: ${{ matrix.build-type }}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./tester
      
