name: Coverage

on: workflow_dispatch

jobs:
  build-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build With Coverage
      uses: ./.github/actions/build
      with:
          build-type: Debug
          with-coverage: true
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./tester
    - name: Install gcovr
      run: sudo apt install -y gcovr
    - name: Report
      working-directory: ${{github.workspace}}
      run: gcovr build/CMakeFiles/inkfuse.dir/src -r src
      
