name: Coverage

on: workflow_dispatch

jobs:
  build-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target tester

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./tester

    - name: Install gcovr
      run: sudo apt install -y gcovr

    - name: Report
      working-directory: ${{github.workspace}}
      run: gcovr build/CMakeFiles/inkfuse.dir/src -r src
      
